version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      PORT: 3000
      # SESUAIKAN DENGAN KONFIGURASI DATABASE DI db_config.js
      DB_HOST: db # PENTING: Ini harus 'db' (nama service database di Docker Compose)
      DB_USER: root
      DB_PASSWORD: "" # PENTING: Sesuai dengan password kosong di db_config.js
      DB_DATABASE: concertrev5 # PENTING: Sesuai dengan nama database di db_config.js
      JWT_SECRET: rahasiaSuperAman123 # Jangan lupa isi ini dari .env lokalmu!
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # Opsional, untuk akses MySQL dari host jika diperlukan
    environment:
      MYSQL_ROOT_PASSWORD: "" # PENTING: Sesuai dengan password kosong di db_config.js
      MYSQL_DATABASE: concertrev5 # PENTING: Sesuai dengan nama database di db_config.js
      MYSQL_USER: root # PENTING: Sesuai dengan user di db_config.js
      MYSQL_PASSWORD: "" # PENTING: Sesuai dengan password kosong di db_config.js
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
