# STEP 1: MEMILIH BASE IMAGE
FROM node:22-alpine

# STEP 2: SET WORKING DIRECTORY
WORKDIR /app

# STEP 3: SALIN FILE MANIFEST DEPENDENSI
COPY package.json ./
COPY package-lock.json ./

# STEP 4: INSTAL DEPENDENSI PROJECT
RUN npm install --production

# STEP 5: SALIN SISA KODE PROJECT
COPY . .

# STEP 6: EXPOSE PORT
EXPOSE 3000

# STEP 7: DEFINISIKAN COMMAND UNTUK MENJALANKAN APLIKASI
CMD ["node", "backend/server.js"]