services:
  app:
    build: .
    image: adinnhd/tixvibe:latest
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/usr/src/app
      - ./src/public:/usr/src/public
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root # Or your preferred user
      - DB_PASSWORD=password # Choose a strong password
      - DB_NAME=concertrev5 # Or your preferred database name

  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    cap_add:
      - SYS_NICE # Fix for MySQL 8 performance issues
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./concertrev5.sql:/docker-entrypoint-initdb.d/concertrev5.sql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password # Choose a strong password
      MYSQL_DATABASE: concertrev5 # Or your preferred database name

volumes:
  db_data: 