version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      PORT: 3000
     
      DB_HOST: db 
      DB_USER: root
      DB_PASSWORD: "" 
      DB_DATABASE: concertrev5 
      JWT_SECRET: rahasiaSuperAman123 
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "" 
      MYSQL_DATABASE: concertrev5 
      MYSQL_USER: root 
      MYSQL_PASSWORD: "" 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
